#! /bin/bash
case ${1} in
si) xrandr --output DP-1 --mode 1920x1080
    xrandr --output eDP-1 --off
    i3 restart
;;
no) xrandr --output eDP-1 --mode 1366x768
    xrandr --output DP-1 --off
    i3 restart
;;
dos)xrandr --output eDP-1 --mode 1366x768
    xrandr --output DP-1 --mode 1920x1080
    xrandr --output DP-1 --primary --right-of eDP-1
    i3 restart
;;
esac
