#!/bin/bash
echo -n ; pactl list | grep -E -o -m -1 [0-9][0-9]%a? | head -1
case $BLOCK_BUTTON in
  1)  pactl set-sink-mute 0 toggle && pkill -RTMIN+3 i3blocks;;  # right click, mute/unmute
  4)  pactl set-sink-volume 0 +5% && pactl set-sink-mute 0 0;; # scroll up, increase
  5)  pactl set-sink-volume 0 -5% && pactl set-sink-mute 0 0;; # scroll down, decrease
esac
